---
- name: mkdir required dirs
  #file: path={{ item }} state=directory recurse=yes mode=0755 owner={{config_user}} group={{config_group}}
  shell: |
    if [ ! -e {{ item }} ]; then
      mkdir -p -m 755 {{ item }}
      chown {{ config_user }}:{{ config_group }} {{ item }}
    fi
  with_items:
    - "{{ devops_pack_path }}"
    - "{{ postgresql_for_gitlab_path }}"
    - "{{ redis_for_gitlab_path }}"
    - "{{ gitlab_path }}/data"
    - "{{ gitlab_path }}/log"
    - "{{ jenkins_data_path }}"
    - "{{ jenkins_slave_path }}/build/slave"
    - "{{ jenkins_slave_path }}/build/jnlp-slave"
    - "{{ jenkins_slave_path }}/data"
    - "{{ openldap_data_path }}/conf"
    - "{{ openldap_data_path }}/data"

- name: docker pull
#  docker_image:
#    name: "{{ item.name }}"
#    tag: "{{ item.tag }}"
  shell: docker pull {{ item.name }}:{{ item.tag }}
  with_items:
    - { name: "sameersbn/postgresql", tag: "{{ postgresql_for_gitlab_version }}" }
    - { name: "sameersbn/redis", tag: "{{ redis_for_gitlab_version }}" }
    - { name: "sameersbn/gitlab", tag: "{{ gitlab_version }}" }
    - { name: "jenkins/jenkins", tag: "{{ jenkins_version }}" }
    - { name: "osixia/openldap", tag: "{{ openldap_version }}" }
    - { name: "osixia/phpldapadmin", tag: "{{ phpldapadmin_version }}" }
    - { name: "sonatype/nexus3", tag: "{{ nexus_version }}" }
    - { name: "openjdk", tag: "{{ jenkins_slave_openjdk_version }}-jdk" }

- name: set Dockerfile etc for jenkins-slave-java
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"
  with_items:
    - { src: "Dockerfile_for_JenkinsSlave-Java.j2", dest: "{{ jenkins_slave_path }}/build/slave/Dockerfile" }
    - { src: "Dockerfile_for_JenkinsJnlpSlave-Java.j2", dest: "{{ jenkins_slave_path }}/build/jnlp-slave/Dockerfile" }
    - { src: "jenkins-slave.j2", dest: "{{ jenkins_slave_path }}/build/jnlp-slave/jenkins-slave" }

- name: docker build
  shell: docker build -t {{ item.tag }} {{ item.dockerfile_path }}
  with_items:
    - { tag: "jenkins-slave-java:openjdk-{{ jenkins_slave_openjdk_version }}", dockerfile_path: "{{ jenkins_slave_path }}/build/slave/" }
    - { tag: "jenkins-jnlp-slave-java:openjdk-{{ jenkins_slave_openjdk_version }}", dockerfile_path: "{{ jenkins_slave_path }}/build/jnlp-slave/" }

- name: set docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ devops_pack_path }}/docker-compose.yml"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"

- name: configure docker container services
  template: src=docker-devops-pack.service.j2 dest=/usr/lib/systemd/system/docker-devops-pack.service

- name: enable docker container services
  service: name=docker-devops-pack enabled=yes state=started
