---
- name: mkdir required dirs
  #file: path={{ item }} state=directory recurse=yes mode=0755 owner={{config_user}} group={{config_group}}
  shell: |
    if [ ! -e {{ item }} ]; then
      mkdir -p -m 755 {{ item }}
      chown {{ config_user }}:{{ config_group }} {{ item }}
    fi
  with_items:
    - "{{ devops_pack_path }}"
    - "{{ postgresql_for_gitlab_path }}"
    - "{{ redis_for_gitlab_path }}"
    - "{{ gitlab_path }}/data"
    - "{{ gitlab_path }}/log"
    - "{{ jenkins_data_path }}"
    - "{{ openldap_data_path }}/conf"
    - "{{ openldap_data_path }}/data"

- name: docker pull
#  docker_image:
#    name: "{{ item.name }}"
#    tag: "{{ item.tag }}"
  shell: docker pull {{ item.name }}:{{ item.tag }}
  with_items:
    - { name: "sameersbn/postgresql", tag: "{{ postgresql_for_gitlab_version }}" }
    - { name: "sameersbn/redis", tag: "{{ redis_for_gitlab_version }}" }
    - { name: "sameersbn/gitlab", tag: "{{ gitlab_version }}" }
    - { name: "jenkins/jenkins", tag: "{{ jenkins_version }}" }
    - { name: "osixia/openldap", tag: "{{ openldap_version }}" }
    - { name: "osixia/phpldapadmin", tag: "{{ phpldapadmin_version }}" }
    - { name: "sonatype/nexus3", tag: "{{ nexus_version }}" }

- name: set docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ devops_pack_path }}/docker-compose.yml"
    owner: "{{ config_user }}"
    group: "{{ config_group }}"

- name: configure docker container services
  template: src=docker-devops-pack.service.j2 dest=/usr/lib/systemd/system/docker-devops-pack.service

- name: enable docker container services
  service: name=docker-devops-pack enabled=yes state=started
