---
- hosts: target
  become: true
  user: vagrant
  vars:
    config_user: "vagrant"
    config_group: "vagrant"
    git_wandisco_repo_distribution: "centos"
    gradle_version: "4.8"
    gradle_path: "/opt/gradle"
    docker_compose_version: "1.21.2"
    devops_pack_path: "/var/lib/docker/data/devops-pack"
    postgresql_for_gitlab_version: "9.6-2"
    postgresql_for_gitlab_path: "/var/lib/docker/data/postgresql_for_gitlab"
    postgresql_for_gitlab_db_name: "gitlab"
    postgresql_for_gitlab_user: "gitlab"
    # postgresql_for_gitlab_pass: ""
    postgresql_for_gitlab_port: 8003
    redis_for_gitlab_version: "latest"
    redis_for_gitlab_path: "/var/lib/docker/data/redis_for_gitlab"
    gitlab_version: "10.8.3-1"
    gitlab_hostname: "localhost"
    gitlab_path: "/var/lib/docker/data/gitlab"
    gitlab_http_port: 8001
    gitlab_ssh_port: 8002
    # gitlab_smtp_user: ""
    # gitlab_smtp_pass: ""
    jenkins_version: "2.107.3"
    jenkins_data_path: "/var/lib/docker/data/jenkins"
    jenkins_http_port: 8004
    jenkins_jnlp_port: 8005
    jenkins_slave_path: "/var/lib/docker/data/jenkins-slave"
    jenkins_slave_openjdk_version: "8u171"
    jenkins_slave_agent_name: ""
    jenkins_slave_secret_token: ""
    openldap_version: "1.2.1"
    openldap_data_path: "/var/lib/docker/data/openldap"
    openldap_port: 8006
    # openldap_admin_pass: ""
    openldap_org_name: "LDAP for example.local"
    openldap_1st_dc: "example"
    openldap_2nd_dc: "local"
    openldap_base_user_ou: "users"
    phpldapadmin_version: "0.7.1"
    phpldapadmin_http_port: 8007
    nexus_version: "3.12.0"
    nexus_volume_name: "nexus"
    nexus_http_port: 8008
    nexus_docker_port: 8009
  vars_files:
    - env_vars.yml
  roles:
    - basic-tools
    - docker
    - docker-compose
    - docker-devops-pack
